#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKHDataService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLKH")]
	public partial class QLKHDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChucVu(ChucVu instance);
    partial void UpdateChucVu(ChucVu instance);
    partial void DeleteChucVu(ChucVu instance);
    partial void InsertSinhNhat(SinhNhat instance);
    partial void UpdateSinhNhat(SinhNhat instance);
    partial void DeleteSinhNhat(SinhNhat instance);
    partial void InsertConNguoi(ConNguoi instance);
    partial void UpdateConNguoi(ConNguoi instance);
    partial void DeleteConNguoi(ConNguoi instance);
    partial void InsertCuocGoi(CuocGoi instance);
    partial void UpdateCuocGoi(CuocGoi instance);
    partial void DeleteCuocGoi(CuocGoi instance);
    partial void InsertDanhSachChucVu(DanhSachChucVu instance);
    partial void UpdateDanhSachChucVu(DanhSachChucVu instance);
    partial void DeleteDanhSachChucVu(DanhSachChucVu instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertLoaiCuocGoi(LoaiCuocGoi instance);
    partial void UpdateLoaiCuocGoi(LoaiCuocGoi instance);
    partial void DeleteLoaiCuocGoi(LoaiCuocGoi instance);
    partial void InsertLoaiKhachHang(LoaiKhachHang instance);
    partial void UpdateLoaiKhachHang(LoaiKhachHang instance);
    partial void DeleteLoaiKhachHang(LoaiKhachHang instance);
    partial void InsertLoaiQuanHe(LoaiQuanHe instance);
    partial void UpdateLoaiQuanHe(LoaiQuanHe instance);
    partial void DeleteLoaiQuanHe(LoaiQuanHe instance);
    partial void InsertMuaHang(MuaHang instance);
    partial void UpdateMuaHang(MuaHang instance);
    partial void DeleteMuaHang(MuaHang instance);
    partial void InsertNguoiThan(NguoiThan instance);
    partial void UpdateNguoiThan(NguoiThan instance);
    partial void DeleteNguoiThan(NguoiThan instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertQuaTang(QuaTang instance);
    partial void UpdateQuaTang(QuaTang instance);
    partial void DeleteQuaTang(QuaTang instance);
    partial void InsertQuyen(Quyen instance);
    partial void UpdateQuyen(Quyen instance);
    partial void DeleteQuyen(Quyen instance);
    #endregion
		
		public QLKHDataContext() : 
				base(global::QLKHDataService.Properties.Settings.Default.QLKHConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLKHDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLKHDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLKHDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLKHDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChucVu> ChucVus
		{
			get
			{
				return this.GetTable<ChucVu>();
			}
		}
		
		public System.Data.Linq.Table<SinhNhat> SinhNhats
		{
			get
			{
				return this.GetTable<SinhNhat>();
			}
		}
		
		public System.Data.Linq.Table<ConNguoi> ConNguois
		{
			get
			{
				return this.GetTable<ConNguoi>();
			}
		}
		
		public System.Data.Linq.Table<CuocGoi> CuocGois
		{
			get
			{
				return this.GetTable<CuocGoi>();
			}
		}
		
		public System.Data.Linq.Table<DanhSachChucVu> DanhSachChucVus
		{
			get
			{
				return this.GetTable<DanhSachChucVu>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<LoaiCuocGoi> LoaiCuocGois
		{
			get
			{
				return this.GetTable<LoaiCuocGoi>();
			}
		}
		
		public System.Data.Linq.Table<LoaiKhachHang> LoaiKhachHangs
		{
			get
			{
				return this.GetTable<LoaiKhachHang>();
			}
		}
		
		public System.Data.Linq.Table<LoaiQuanHe> LoaiQuanHes
		{
			get
			{
				return this.GetTable<LoaiQuanHe>();
			}
		}
		
		public System.Data.Linq.Table<MuaHang> MuaHangs
		{
			get
			{
				return this.GetTable<MuaHang>();
			}
		}
		
		public System.Data.Linq.Table<NguoiThan> NguoiThans
		{
			get
			{
				return this.GetTable<NguoiThan>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<QuaTang> QuaTangs
		{
			get
			{
				return this.GetTable<QuaTang>();
			}
		}
		
		public System.Data.Linq.Table<Quyen> Quyens
		{
			get
			{
				return this.GetTable<Quyen>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChucVu")]
	public partial class ChucVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ChucVuID;
		
		private string _TenChucVu;
		
		private System.Nullable<int> _QuyenID;
		
		private EntitySet<DanhSachChucVu> _DanhSachChucVus;
		
		private EntityRef<Quyen> _Quyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnChucVuIDChanging(int value);
    partial void OnChucVuIDChanged();
    partial void OnTenChucVuChanging(string value);
    partial void OnTenChucVuChanged();
    partial void OnQuyenIDChanging(System.Nullable<int> value);
    partial void OnQuyenIDChanged();
    #endregion
		
		public ChucVu()
		{
			this._DanhSachChucVus = new EntitySet<DanhSachChucVu>(new Action<DanhSachChucVu>(this.attach_DanhSachChucVus), new Action<DanhSachChucVu>(this.detach_DanhSachChucVus));
			this._Quyen = default(EntityRef<Quyen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVuID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ChucVuID
		{
			get
			{
				return this._ChucVuID;
			}
			set
			{
				if ((this._ChucVuID != value))
				{
					this.OnChucVuIDChanging(value);
					this.SendPropertyChanging();
					this._ChucVuID = value;
					this.SendPropertyChanged("ChucVuID");
					this.OnChucVuIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenChucVu", DbType="NVarChar(50)")]
		public string TenChucVu
		{
			get
			{
				return this._TenChucVu;
			}
			set
			{
				if ((this._TenChucVu != value))
				{
					this.OnTenChucVuChanging(value);
					this.SendPropertyChanging();
					this._TenChucVu = value;
					this.SendPropertyChanged("TenChucVu");
					this.OnTenChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuyenID", DbType="Int")]
		public System.Nullable<int> QuyenID
		{
			get
			{
				return this._QuyenID;
			}
			set
			{
				if ((this._QuyenID != value))
				{
					if (this._Quyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnQuyenIDChanging(value);
					this.SendPropertyChanging();
					this._QuyenID = value;
					this.SendPropertyChanged("QuyenID");
					this.OnQuyenIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChucVu_DanhSachChucVu", Storage="_DanhSachChucVus", ThisKey="ChucVuID", OtherKey="ChucVuID")]
		public EntitySet<DanhSachChucVu> DanhSachChucVus
		{
			get
			{
				return this._DanhSachChucVus;
			}
			set
			{
				this._DanhSachChucVus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Quyen_ChucVu", Storage="_Quyen", ThisKey="QuyenID", OtherKey="QuyenID", IsForeignKey=true)]
		public Quyen Quyen
		{
			get
			{
				return this._Quyen.Entity;
			}
			set
			{
				Quyen previousValue = this._Quyen.Entity;
				if (((previousValue != value) 
							|| (this._Quyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Quyen.Entity = null;
						previousValue.ChucVus.Remove(this);
					}
					this._Quyen.Entity = value;
					if ((value != null))
					{
						value.ChucVus.Add(this);
						this._QuyenID = value.QuyenID;
					}
					else
					{
						this._QuyenID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Quyen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DanhSachChucVus(DanhSachChucVu entity)
		{
			this.SendPropertyChanging();
			entity.ChucVu = this;
		}
		
		private void detach_DanhSachChucVus(DanhSachChucVu entity)
		{
			this.SendPropertyChanging();
			entity.ChucVu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SinhNhat")]
	public partial class SinhNhat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _KhachHangID;
		
		private bool _DaGoi;
		
		private EntityRef<KhachHang> _KhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKhachHangIDChanging(int value);
    partial void OnKhachHangIDChanged();
    partial void OnDaGoiChanging(bool value);
    partial void OnDaGoiChanged();
    #endregion
		
		public SinhNhat()
		{
			this._KhachHang = default(EntityRef<KhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhachHangID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int KhachHangID
		{
			get
			{
				return this._KhachHangID;
			}
			set
			{
				if ((this._KhachHangID != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKhachHangIDChanging(value);
					this.SendPropertyChanging();
					this._KhachHangID = value;
					this.SendPropertyChanged("KhachHangID");
					this.OnKhachHangIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaGoi", DbType="Bit NOT NULL")]
		public bool DaGoi
		{
			get
			{
				return this._DaGoi;
			}
			set
			{
				if ((this._DaGoi != value))
				{
					this.OnDaGoiChanging(value);
					this.SendPropertyChanging();
					this._DaGoi = value;
					this.SendPropertyChanged("DaGoi");
					this.OnDaGoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_SinhNhat", Storage="_KhachHang", ThisKey="KhachHangID", OtherKey="KhachHangID", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.SinhNhat = null;
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.SinhNhat = this;
						this._KhachHangID = value.KhachHangID;
					}
					else
					{
						this._KhachHangID = default(int);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ConNguoi")]
	public partial class ConNguoi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ConNguoiID;
		
		private string _CMND;
		
		private string _HoTen;
		
		private string _DiaChi;
		
		private System.Nullable<bool> _GioiTinh;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _Phone;
		
		private string _Phone2;
		
		private string _Email;
		
		private string _MatKhau;
		
		private EntitySet<KhachHang> _KhachHangs;
		
		private EntitySet<NguoiThan> _NguoiThans;
		
		private EntitySet<NhanVien> _NhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnConNguoiIDChanging(int value);
    partial void OnConNguoiIDChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnGioiTinhChanging(System.Nullable<bool> value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnPhone2Changing(string value);
    partial void OnPhone2Changed();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    #endregion
		
		public ConNguoi()
		{
			this._KhachHangs = new EntitySet<KhachHang>(new Action<KhachHang>(this.attach_KhachHangs), new Action<KhachHang>(this.detach_KhachHangs));
			this._NguoiThans = new EntitySet<NguoiThan>(new Action<NguoiThan>(this.attach_NguoiThans), new Action<NguoiThan>(this.detach_NguoiThans));
			this._NhanViens = new EntitySet<NhanVien>(new Action<NhanVien>(this.attach_NhanViens), new Action<NhanVien>(this.detach_NhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConNguoiID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ConNguoiID
		{
			get
			{
				return this._ConNguoiID;
			}
			set
			{
				if ((this._ConNguoiID != value))
				{
					this.OnConNguoiIDChanging(value);
					this.SendPropertyChanging();
					this._ConNguoiID = value;
					this.SendPropertyChanged("ConNguoiID");
					this.OnConNguoiIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="VarChar(12)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(100)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(MAX)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Bit")]
		public System.Nullable<bool> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(15)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone2", DbType="VarChar(15)")]
		public string Phone2
		{
			get
			{
				return this._Phone2;
			}
			set
			{
				if ((this._Phone2 != value))
				{
					this.OnPhone2Changing(value);
					this.SendPropertyChanging();
					this._Phone2 = value;
					this.SendPropertyChanged("Phone2");
					this.OnPhone2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(32)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ConNguoi_KhachHang", Storage="_KhachHangs", ThisKey="ConNguoiID", OtherKey="ConNguoiID")]
		public EntitySet<KhachHang> KhachHangs
		{
			get
			{
				return this._KhachHangs;
			}
			set
			{
				this._KhachHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ConNguoi_NguoiThan", Storage="_NguoiThans", ThisKey="ConNguoiID", OtherKey="ConNguoiID")]
		public EntitySet<NguoiThan> NguoiThans
		{
			get
			{
				return this._NguoiThans;
			}
			set
			{
				this._NguoiThans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ConNguoi_NhanVien", Storage="_NhanViens", ThisKey="ConNguoiID", OtherKey="ConNguoiID")]
		public EntitySet<NhanVien> NhanViens
		{
			get
			{
				return this._NhanViens;
			}
			set
			{
				this._NhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KhachHangs(KhachHang entity)
		{
			this.SendPropertyChanging();
			entity.ConNguoi = this;
		}
		
		private void detach_KhachHangs(KhachHang entity)
		{
			this.SendPropertyChanging();
			entity.ConNguoi = null;
		}
		
		private void attach_NguoiThans(NguoiThan entity)
		{
			this.SendPropertyChanging();
			entity.ConNguoi = this;
		}
		
		private void detach_NguoiThans(NguoiThan entity)
		{
			this.SendPropertyChanging();
			entity.ConNguoi = null;
		}
		
		private void attach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.ConNguoi = this;
		}
		
		private void detach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.ConNguoi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CuocGoi")]
	public partial class CuocGoi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _KhachHangID;
		
		private System.DateTime _ThoiDiemGoi;
		
		private System.DateTime _ThoiDiemKetThuc;
		
		private string _GhiChu;
		
		private int _NhanVienID;
		
		private int _LoaiCuocGoiID;
		
		private int _TragThaiKH;
		
		private int _CuocGoiID;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<LoaiCuocGoi> _LoaiCuocGoi;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKhachHangIDChanging(int value);
    partial void OnKhachHangIDChanged();
    partial void OnThoiDiemGoiChanging(System.DateTime value);
    partial void OnThoiDiemGoiChanged();
    partial void OnThoiDiemKetThucChanging(System.DateTime value);
    partial void OnThoiDiemKetThucChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnNhanVienIDChanging(int value);
    partial void OnNhanVienIDChanged();
    partial void OnLoaiCuocGoiIDChanging(int value);
    partial void OnLoaiCuocGoiIDChanged();
    partial void OnTragThaiKHChanging(int value);
    partial void OnTragThaiKHChanged();
    partial void OnCuocGoiIDChanging(int value);
    partial void OnCuocGoiIDChanged();
    #endregion
		
		public CuocGoi()
		{
			this._KhachHang = default(EntityRef<KhachHang>);
			this._LoaiCuocGoi = default(EntityRef<LoaiCuocGoi>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhachHangID", DbType="Int NOT NULL")]
		public int KhachHangID
		{
			get
			{
				return this._KhachHangID;
			}
			set
			{
				if ((this._KhachHangID != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKhachHangIDChanging(value);
					this.SendPropertyChanging();
					this._KhachHangID = value;
					this.SendPropertyChanged("KhachHangID");
					this.OnKhachHangIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiDiemGoi", DbType="DateTime NOT NULL")]
		public System.DateTime ThoiDiemGoi
		{
			get
			{
				return this._ThoiDiemGoi;
			}
			set
			{
				if ((this._ThoiDiemGoi != value))
				{
					this.OnThoiDiemGoiChanging(value);
					this.SendPropertyChanging();
					this._ThoiDiemGoi = value;
					this.SendPropertyChanged("ThoiDiemGoi");
					this.OnThoiDiemGoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiDiemKetThuc", DbType="DateTime NOT NULL")]
		public System.DateTime ThoiDiemKetThuc
		{
			get
			{
				return this._ThoiDiemKetThuc;
			}
			set
			{
				if ((this._ThoiDiemKetThuc != value))
				{
					this.OnThoiDiemKetThucChanging(value);
					this.SendPropertyChanging();
					this._ThoiDiemKetThuc = value;
					this.SendPropertyChanged("ThoiDiemKetThuc");
					this.OnThoiDiemKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhanVienID", DbType="Int NOT NULL")]
		public int NhanVienID
		{
			get
			{
				return this._NhanVienID;
			}
			set
			{
				if ((this._NhanVienID != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNhanVienIDChanging(value);
					this.SendPropertyChanging();
					this._NhanVienID = value;
					this.SendPropertyChanged("NhanVienID");
					this.OnNhanVienIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiCuocGoiID", DbType="Int NOT NULL")]
		public int LoaiCuocGoiID
		{
			get
			{
				return this._LoaiCuocGoiID;
			}
			set
			{
				if ((this._LoaiCuocGoiID != value))
				{
					if (this._LoaiCuocGoi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLoaiCuocGoiIDChanging(value);
					this.SendPropertyChanging();
					this._LoaiCuocGoiID = value;
					this.SendPropertyChanged("LoaiCuocGoiID");
					this.OnLoaiCuocGoiIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TragThaiKH", DbType="Int NOT NULL")]
		public int TragThaiKH
		{
			get
			{
				return this._TragThaiKH;
			}
			set
			{
				if ((this._TragThaiKH != value))
				{
					this.OnTragThaiKHChanging(value);
					this.SendPropertyChanging();
					this._TragThaiKH = value;
					this.SendPropertyChanged("TragThaiKH");
					this.OnTragThaiKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuocGoiID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CuocGoiID
		{
			get
			{
				return this._CuocGoiID;
			}
			set
			{
				if ((this._CuocGoiID != value))
				{
					this.OnCuocGoiIDChanging(value);
					this.SendPropertyChanging();
					this._CuocGoiID = value;
					this.SendPropertyChanged("CuocGoiID");
					this.OnCuocGoiIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_CuocGoi", Storage="_KhachHang", ThisKey="KhachHangID", OtherKey="KhachHangID", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.CuocGois.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.CuocGois.Add(this);
						this._KhachHangID = value.KhachHangID;
					}
					else
					{
						this._KhachHangID = default(int);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiCuocGoi_CuocGoi", Storage="_LoaiCuocGoi", ThisKey="LoaiCuocGoiID", OtherKey="LoaiCuocGoiID", IsForeignKey=true)]
		public LoaiCuocGoi LoaiCuocGoi
		{
			get
			{
				return this._LoaiCuocGoi.Entity;
			}
			set
			{
				LoaiCuocGoi previousValue = this._LoaiCuocGoi.Entity;
				if (((previousValue != value) 
							|| (this._LoaiCuocGoi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiCuocGoi.Entity = null;
						previousValue.CuocGois.Remove(this);
					}
					this._LoaiCuocGoi.Entity = value;
					if ((value != null))
					{
						value.CuocGois.Add(this);
						this._LoaiCuocGoiID = value.LoaiCuocGoiID;
					}
					else
					{
						this._LoaiCuocGoiID = default(int);
					}
					this.SendPropertyChanged("LoaiCuocGoi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_CuocGoi", Storage="_NhanVien", ThisKey="NhanVienID", OtherKey="NhanVienID", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.CuocGois.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.CuocGois.Add(this);
						this._NhanVienID = value.NhanVienID;
					}
					else
					{
						this._NhanVienID = default(int);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DanhSachChucVu")]
	public partial class DanhSachChucVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _NhanVienID;
		
		private int _ChucVuID;
		
		private EntityRef<ChucVu> _ChucVu;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNhanVienIDChanging(int value);
    partial void OnNhanVienIDChanged();
    partial void OnChucVuIDChanging(int value);
    partial void OnChucVuIDChanged();
    #endregion
		
		public DanhSachChucVu()
		{
			this._ChucVu = default(EntityRef<ChucVu>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhanVienID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int NhanVienID
		{
			get
			{
				return this._NhanVienID;
			}
			set
			{
				if ((this._NhanVienID != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNhanVienIDChanging(value);
					this.SendPropertyChanging();
					this._NhanVienID = value;
					this.SendPropertyChanged("NhanVienID");
					this.OnNhanVienIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVuID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ChucVuID
		{
			get
			{
				return this._ChucVuID;
			}
			set
			{
				if ((this._ChucVuID != value))
				{
					if (this._ChucVu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnChucVuIDChanging(value);
					this.SendPropertyChanging();
					this._ChucVuID = value;
					this.SendPropertyChanged("ChucVuID");
					this.OnChucVuIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChucVu_DanhSachChucVu", Storage="_ChucVu", ThisKey="ChucVuID", OtherKey="ChucVuID", IsForeignKey=true)]
		public ChucVu ChucVu
		{
			get
			{
				return this._ChucVu.Entity;
			}
			set
			{
				ChucVu previousValue = this._ChucVu.Entity;
				if (((previousValue != value) 
							|| (this._ChucVu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChucVu.Entity = null;
						previousValue.DanhSachChucVus.Remove(this);
					}
					this._ChucVu.Entity = value;
					if ((value != null))
					{
						value.DanhSachChucVus.Add(this);
						this._ChucVuID = value.ChucVuID;
					}
					else
					{
						this._ChucVuID = default(int);
					}
					this.SendPropertyChanged("ChucVu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_DanhSachChucVu", Storage="_NhanVien", ThisKey="NhanVienID", OtherKey="NhanVienID", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.DanhSachChucVus.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.DanhSachChucVus.Add(this);
						this._NhanVienID = value.NhanVienID;
					}
					else
					{
						this._NhanVienID = default(int);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _KhachHangID;
		
		private System.Nullable<int> _TongGTGiaoDich;
		
		private int _ConNguoiID;
		
		private System.Nullable<int> _LoaiKhachHangID;
		
		private EntityRef<SinhNhat> _SinhNhat;
		
		private EntitySet<CuocGoi> _CuocGois;
		
		private EntitySet<MuaHang> _MuaHangs;
		
		private EntitySet<NguoiThan> _NguoiThans;
		
		private EntitySet<QuaTang> _QuaTangs;
		
		private EntityRef<ConNguoi> _ConNguoi;
		
		private EntityRef<LoaiKhachHang> _LoaiKhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKhachHangIDChanging(int value);
    partial void OnKhachHangIDChanged();
    partial void OnTongGTGiaoDichChanging(System.Nullable<int> value);
    partial void OnTongGTGiaoDichChanged();
    partial void OnConNguoiIDChanging(int value);
    partial void OnConNguoiIDChanged();
    partial void OnLoaiKhachHangIDChanging(System.Nullable<int> value);
    partial void OnLoaiKhachHangIDChanged();
    #endregion
		
		public KhachHang()
		{
			this._SinhNhat = default(EntityRef<SinhNhat>);
			this._CuocGois = new EntitySet<CuocGoi>(new Action<CuocGoi>(this.attach_CuocGois), new Action<CuocGoi>(this.detach_CuocGois));
			this._MuaHangs = new EntitySet<MuaHang>(new Action<MuaHang>(this.attach_MuaHangs), new Action<MuaHang>(this.detach_MuaHangs));
			this._NguoiThans = new EntitySet<NguoiThan>(new Action<NguoiThan>(this.attach_NguoiThans), new Action<NguoiThan>(this.detach_NguoiThans));
			this._QuaTangs = new EntitySet<QuaTang>(new Action<QuaTang>(this.attach_QuaTangs), new Action<QuaTang>(this.detach_QuaTangs));
			this._ConNguoi = default(EntityRef<ConNguoi>);
			this._LoaiKhachHang = default(EntityRef<LoaiKhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhachHangID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int KhachHangID
		{
			get
			{
				return this._KhachHangID;
			}
			set
			{
				if ((this._KhachHangID != value))
				{
					this.OnKhachHangIDChanging(value);
					this.SendPropertyChanging();
					this._KhachHangID = value;
					this.SendPropertyChanged("KhachHangID");
					this.OnKhachHangIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongGTGiaoDich", DbType="Int")]
		public System.Nullable<int> TongGTGiaoDich
		{
			get
			{
				return this._TongGTGiaoDich;
			}
			set
			{
				if ((this._TongGTGiaoDich != value))
				{
					this.OnTongGTGiaoDichChanging(value);
					this.SendPropertyChanging();
					this._TongGTGiaoDich = value;
					this.SendPropertyChanged("TongGTGiaoDich");
					this.OnTongGTGiaoDichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConNguoiID", DbType="Int NOT NULL")]
		public int ConNguoiID
		{
			get
			{
				return this._ConNguoiID;
			}
			set
			{
				if ((this._ConNguoiID != value))
				{
					if (this._ConNguoi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnConNguoiIDChanging(value);
					this.SendPropertyChanging();
					this._ConNguoiID = value;
					this.SendPropertyChanged("ConNguoiID");
					this.OnConNguoiIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiKhachHangID", DbType="Int")]
		public System.Nullable<int> LoaiKhachHangID
		{
			get
			{
				return this._LoaiKhachHangID;
			}
			set
			{
				if ((this._LoaiKhachHangID != value))
				{
					if (this._LoaiKhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLoaiKhachHangIDChanging(value);
					this.SendPropertyChanging();
					this._LoaiKhachHangID = value;
					this.SendPropertyChanged("LoaiKhachHangID");
					this.OnLoaiKhachHangIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_SinhNhat", Storage="_SinhNhat", ThisKey="KhachHangID", OtherKey="KhachHangID", IsUnique=true, IsForeignKey=false)]
		public SinhNhat SinhNhat
		{
			get
			{
				return this._SinhNhat.Entity;
			}
			set
			{
				SinhNhat previousValue = this._SinhNhat.Entity;
				if (((previousValue != value) 
							|| (this._SinhNhat.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SinhNhat.Entity = null;
						previousValue.KhachHang = null;
					}
					this._SinhNhat.Entity = value;
					if ((value != null))
					{
						value.KhachHang = this;
					}
					this.SendPropertyChanged("SinhNhat");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_CuocGoi", Storage="_CuocGois", ThisKey="KhachHangID", OtherKey="KhachHangID")]
		public EntitySet<CuocGoi> CuocGois
		{
			get
			{
				return this._CuocGois;
			}
			set
			{
				this._CuocGois.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_MuaHang", Storage="_MuaHangs", ThisKey="KhachHangID", OtherKey="KhachHangID")]
		public EntitySet<MuaHang> MuaHangs
		{
			get
			{
				return this._MuaHangs;
			}
			set
			{
				this._MuaHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_NguoiThan", Storage="_NguoiThans", ThisKey="KhachHangID", OtherKey="KhachHangID")]
		public EntitySet<NguoiThan> NguoiThans
		{
			get
			{
				return this._NguoiThans;
			}
			set
			{
				this._NguoiThans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_QuaTang", Storage="_QuaTangs", ThisKey="KhachHangID", OtherKey="KHID")]
		public EntitySet<QuaTang> QuaTangs
		{
			get
			{
				return this._QuaTangs;
			}
			set
			{
				this._QuaTangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ConNguoi_KhachHang", Storage="_ConNguoi", ThisKey="ConNguoiID", OtherKey="ConNguoiID", IsForeignKey=true)]
		public ConNguoi ConNguoi
		{
			get
			{
				return this._ConNguoi.Entity;
			}
			set
			{
				ConNguoi previousValue = this._ConNguoi.Entity;
				if (((previousValue != value) 
							|| (this._ConNguoi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ConNguoi.Entity = null;
						previousValue.KhachHangs.Remove(this);
					}
					this._ConNguoi.Entity = value;
					if ((value != null))
					{
						value.KhachHangs.Add(this);
						this._ConNguoiID = value.ConNguoiID;
					}
					else
					{
						this._ConNguoiID = default(int);
					}
					this.SendPropertyChanged("ConNguoi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiKhachHang_KhachHang", Storage="_LoaiKhachHang", ThisKey="LoaiKhachHangID", OtherKey="LoaiKhachHangID", IsForeignKey=true)]
		public LoaiKhachHang LoaiKhachHang
		{
			get
			{
				return this._LoaiKhachHang.Entity;
			}
			set
			{
				LoaiKhachHang previousValue = this._LoaiKhachHang.Entity;
				if (((previousValue != value) 
							|| (this._LoaiKhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiKhachHang.Entity = null;
						previousValue.KhachHangs.Remove(this);
					}
					this._LoaiKhachHang.Entity = value;
					if ((value != null))
					{
						value.KhachHangs.Add(this);
						this._LoaiKhachHangID = value.LoaiKhachHangID;
					}
					else
					{
						this._LoaiKhachHangID = default(Nullable<int>);
					}
					this.SendPropertyChanged("LoaiKhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CuocGois(CuocGoi entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_CuocGois(CuocGoi entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
		
		private void attach_MuaHangs(MuaHang entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_MuaHangs(MuaHang entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
		
		private void attach_NguoiThans(NguoiThan entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_NguoiThans(NguoiThan entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
		
		private void attach_QuaTangs(QuaTang entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_QuaTangs(QuaTang entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiCuocGoi")]
	public partial class LoaiCuocGoi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LoaiCuocGoiID;
		
		private string _TenLoaiCuocGoi;
		
		private EntitySet<CuocGoi> _CuocGois;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLoaiCuocGoiIDChanging(int value);
    partial void OnLoaiCuocGoiIDChanged();
    partial void OnTenLoaiCuocGoiChanging(string value);
    partial void OnTenLoaiCuocGoiChanged();
    #endregion
		
		public LoaiCuocGoi()
		{
			this._CuocGois = new EntitySet<CuocGoi>(new Action<CuocGoi>(this.attach_CuocGois), new Action<CuocGoi>(this.detach_CuocGois));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiCuocGoiID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LoaiCuocGoiID
		{
			get
			{
				return this._LoaiCuocGoiID;
			}
			set
			{
				if ((this._LoaiCuocGoiID != value))
				{
					this.OnLoaiCuocGoiIDChanging(value);
					this.SendPropertyChanging();
					this._LoaiCuocGoiID = value;
					this.SendPropertyChanged("LoaiCuocGoiID");
					this.OnLoaiCuocGoiIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiCuocGoi", DbType="NVarChar(50)")]
		public string TenLoaiCuocGoi
		{
			get
			{
				return this._TenLoaiCuocGoi;
			}
			set
			{
				if ((this._TenLoaiCuocGoi != value))
				{
					this.OnTenLoaiCuocGoiChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiCuocGoi = value;
					this.SendPropertyChanged("TenLoaiCuocGoi");
					this.OnTenLoaiCuocGoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiCuocGoi_CuocGoi", Storage="_CuocGois", ThisKey="LoaiCuocGoiID", OtherKey="LoaiCuocGoiID")]
		public EntitySet<CuocGoi> CuocGois
		{
			get
			{
				return this._CuocGois;
			}
			set
			{
				this._CuocGois.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CuocGois(CuocGoi entity)
		{
			this.SendPropertyChanging();
			entity.LoaiCuocGoi = this;
		}
		
		private void detach_CuocGois(CuocGoi entity)
		{
			this.SendPropertyChanging();
			entity.LoaiCuocGoi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiKhachHang")]
	public partial class LoaiKhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LoaiKhachHangID;
		
		private string _TenLoaiKhachHang;
		
		private EntitySet<KhachHang> _KhachHangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLoaiKhachHangIDChanging(int value);
    partial void OnLoaiKhachHangIDChanged();
    partial void OnTenLoaiKhachHangChanging(string value);
    partial void OnTenLoaiKhachHangChanged();
    #endregion
		
		public LoaiKhachHang()
		{
			this._KhachHangs = new EntitySet<KhachHang>(new Action<KhachHang>(this.attach_KhachHangs), new Action<KhachHang>(this.detach_KhachHangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiKhachHangID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LoaiKhachHangID
		{
			get
			{
				return this._LoaiKhachHangID;
			}
			set
			{
				if ((this._LoaiKhachHangID != value))
				{
					this.OnLoaiKhachHangIDChanging(value);
					this.SendPropertyChanging();
					this._LoaiKhachHangID = value;
					this.SendPropertyChanged("LoaiKhachHangID");
					this.OnLoaiKhachHangIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiKhachHang", DbType="NVarChar(50)")]
		public string TenLoaiKhachHang
		{
			get
			{
				return this._TenLoaiKhachHang;
			}
			set
			{
				if ((this._TenLoaiKhachHang != value))
				{
					this.OnTenLoaiKhachHangChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiKhachHang = value;
					this.SendPropertyChanged("TenLoaiKhachHang");
					this.OnTenLoaiKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiKhachHang_KhachHang", Storage="_KhachHangs", ThisKey="LoaiKhachHangID", OtherKey="LoaiKhachHangID")]
		public EntitySet<KhachHang> KhachHangs
		{
			get
			{
				return this._KhachHangs;
			}
			set
			{
				this._KhachHangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KhachHangs(KhachHang entity)
		{
			this.SendPropertyChanging();
			entity.LoaiKhachHang = this;
		}
		
		private void detach_KhachHangs(KhachHang entity)
		{
			this.SendPropertyChanging();
			entity.LoaiKhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiQuanHe")]
	public partial class LoaiQuanHe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LoaiQuanHeID;
		
		private string _TenQuanHe;
		
		private EntitySet<NguoiThan> _NguoiThans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLoaiQuanHeIDChanging(int value);
    partial void OnLoaiQuanHeIDChanged();
    partial void OnTenQuanHeChanging(string value);
    partial void OnTenQuanHeChanged();
    #endregion
		
		public LoaiQuanHe()
		{
			this._NguoiThans = new EntitySet<NguoiThan>(new Action<NguoiThan>(this.attach_NguoiThans), new Action<NguoiThan>(this.detach_NguoiThans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiQuanHeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LoaiQuanHeID
		{
			get
			{
				return this._LoaiQuanHeID;
			}
			set
			{
				if ((this._LoaiQuanHeID != value))
				{
					this.OnLoaiQuanHeIDChanging(value);
					this.SendPropertyChanging();
					this._LoaiQuanHeID = value;
					this.SendPropertyChanged("LoaiQuanHeID");
					this.OnLoaiQuanHeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQuanHe", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenQuanHe
		{
			get
			{
				return this._TenQuanHe;
			}
			set
			{
				if ((this._TenQuanHe != value))
				{
					this.OnTenQuanHeChanging(value);
					this.SendPropertyChanging();
					this._TenQuanHe = value;
					this.SendPropertyChanged("TenQuanHe");
					this.OnTenQuanHeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiQuanHe_NguoiThan", Storage="_NguoiThans", ThisKey="LoaiQuanHeID", OtherKey="LoaiQuanHeID")]
		public EntitySet<NguoiThan> NguoiThans
		{
			get
			{
				return this._NguoiThans;
			}
			set
			{
				this._NguoiThans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NguoiThans(NguoiThan entity)
		{
			this.SendPropertyChanging();
			entity.LoaiQuanHe = this;
		}
		
		private void detach_NguoiThans(NguoiThan entity)
		{
			this.SendPropertyChanging();
			entity.LoaiQuanHe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MuaHang")]
	public partial class MuaHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _KhachHangID;
		
		private int _MaMuaHang;
		
		private System.Nullable<int> _GiaTri;
		
		private System.Nullable<System.DateTime> _NgayMua;
		
		private EntityRef<KhachHang> _KhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKhachHangIDChanging(int value);
    partial void OnKhachHangIDChanged();
    partial void OnMaMuaHangChanging(int value);
    partial void OnMaMuaHangChanged();
    partial void OnGiaTriChanging(System.Nullable<int> value);
    partial void OnGiaTriChanged();
    partial void OnNgayMuaChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayMuaChanged();
    #endregion
		
		public MuaHang()
		{
			this._KhachHang = default(EntityRef<KhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhachHangID", DbType="Int NOT NULL")]
		public int KhachHangID
		{
			get
			{
				return this._KhachHangID;
			}
			set
			{
				if ((this._KhachHangID != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKhachHangIDChanging(value);
					this.SendPropertyChanging();
					this._KhachHangID = value;
					this.SendPropertyChanged("KhachHangID");
					this.OnKhachHangIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMuaHang", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaMuaHang
		{
			get
			{
				return this._MaMuaHang;
			}
			set
			{
				if ((this._MaMuaHang != value))
				{
					this.OnMaMuaHangChanging(value);
					this.SendPropertyChanging();
					this._MaMuaHang = value;
					this.SendPropertyChanged("MaMuaHang");
					this.OnMaMuaHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTri", DbType="Int")]
		public System.Nullable<int> GiaTri
		{
			get
			{
				return this._GiaTri;
			}
			set
			{
				if ((this._GiaTri != value))
				{
					this.OnGiaTriChanging(value);
					this.SendPropertyChanging();
					this._GiaTri = value;
					this.SendPropertyChanged("GiaTri");
					this.OnGiaTriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayMua", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayMua
		{
			get
			{
				return this._NgayMua;
			}
			set
			{
				if ((this._NgayMua != value))
				{
					this.OnNgayMuaChanging(value);
					this.SendPropertyChanging();
					this._NgayMua = value;
					this.SendPropertyChanged("NgayMua");
					this.OnNgayMuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_MuaHang", Storage="_KhachHang", ThisKey="KhachHangID", OtherKey="KhachHangID", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.MuaHangs.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.MuaHangs.Add(this);
						this._KhachHangID = value.KhachHangID;
					}
					else
					{
						this._KhachHangID = default(int);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiThan")]
	public partial class NguoiThan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _NguoiThanID;
		
		private int _KhachHangID;
		
		private int _LoaiQuanHeID;
		
		private int _ConNguoiID;
		
		private EntityRef<ConNguoi> _ConNguoi;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<LoaiQuanHe> _LoaiQuanHe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNguoiThanIDChanging(int value);
    partial void OnNguoiThanIDChanged();
    partial void OnKhachHangIDChanging(int value);
    partial void OnKhachHangIDChanged();
    partial void OnLoaiQuanHeIDChanging(int value);
    partial void OnLoaiQuanHeIDChanged();
    partial void OnConNguoiIDChanging(int value);
    partial void OnConNguoiIDChanged();
    #endregion
		
		public NguoiThan()
		{
			this._ConNguoi = default(EntityRef<ConNguoi>);
			this._KhachHang = default(EntityRef<KhachHang>);
			this._LoaiQuanHe = default(EntityRef<LoaiQuanHe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiThanID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int NguoiThanID
		{
			get
			{
				return this._NguoiThanID;
			}
			set
			{
				if ((this._NguoiThanID != value))
				{
					this.OnNguoiThanIDChanging(value);
					this.SendPropertyChanging();
					this._NguoiThanID = value;
					this.SendPropertyChanged("NguoiThanID");
					this.OnNguoiThanIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhachHangID", DbType="Int NOT NULL")]
		public int KhachHangID
		{
			get
			{
				return this._KhachHangID;
			}
			set
			{
				if ((this._KhachHangID != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKhachHangIDChanging(value);
					this.SendPropertyChanging();
					this._KhachHangID = value;
					this.SendPropertyChanged("KhachHangID");
					this.OnKhachHangIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiQuanHeID", DbType="Int NOT NULL")]
		public int LoaiQuanHeID
		{
			get
			{
				return this._LoaiQuanHeID;
			}
			set
			{
				if ((this._LoaiQuanHeID != value))
				{
					if (this._LoaiQuanHe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLoaiQuanHeIDChanging(value);
					this.SendPropertyChanging();
					this._LoaiQuanHeID = value;
					this.SendPropertyChanged("LoaiQuanHeID");
					this.OnLoaiQuanHeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConNguoiID", DbType="Int NOT NULL")]
		public int ConNguoiID
		{
			get
			{
				return this._ConNguoiID;
			}
			set
			{
				if ((this._ConNguoiID != value))
				{
					if (this._ConNguoi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnConNguoiIDChanging(value);
					this.SendPropertyChanging();
					this._ConNguoiID = value;
					this.SendPropertyChanged("ConNguoiID");
					this.OnConNguoiIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ConNguoi_NguoiThan", Storage="_ConNguoi", ThisKey="ConNguoiID", OtherKey="ConNguoiID", IsForeignKey=true)]
		public ConNguoi ConNguoi
		{
			get
			{
				return this._ConNguoi.Entity;
			}
			set
			{
				ConNguoi previousValue = this._ConNguoi.Entity;
				if (((previousValue != value) 
							|| (this._ConNguoi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ConNguoi.Entity = null;
						previousValue.NguoiThans.Remove(this);
					}
					this._ConNguoi.Entity = value;
					if ((value != null))
					{
						value.NguoiThans.Add(this);
						this._ConNguoiID = value.ConNguoiID;
					}
					else
					{
						this._ConNguoiID = default(int);
					}
					this.SendPropertyChanged("ConNguoi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_NguoiThan", Storage="_KhachHang", ThisKey="KhachHangID", OtherKey="KhachHangID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.NguoiThans.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.NguoiThans.Add(this);
						this._KhachHangID = value.KhachHangID;
					}
					else
					{
						this._KhachHangID = default(int);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiQuanHe_NguoiThan", Storage="_LoaiQuanHe", ThisKey="LoaiQuanHeID", OtherKey="LoaiQuanHeID", IsForeignKey=true)]
		public LoaiQuanHe LoaiQuanHe
		{
			get
			{
				return this._LoaiQuanHe.Entity;
			}
			set
			{
				LoaiQuanHe previousValue = this._LoaiQuanHe.Entity;
				if (((previousValue != value) 
							|| (this._LoaiQuanHe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiQuanHe.Entity = null;
						previousValue.NguoiThans.Remove(this);
					}
					this._LoaiQuanHe.Entity = value;
					if ((value != null))
					{
						value.NguoiThans.Add(this);
						this._LoaiQuanHeID = value.LoaiQuanHeID;
					}
					else
					{
						this._LoaiQuanHeID = default(int);
					}
					this.SendPropertyChanged("LoaiQuanHe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _NhanVienID;
		
		private int _ConNguoiID;
		
		private EntitySet<CuocGoi> _CuocGois;
		
		private EntitySet<DanhSachChucVu> _DanhSachChucVus;
		
		private EntitySet<QuaTang> _QuaTangs;
		
		private EntityRef<ConNguoi> _ConNguoi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNhanVienIDChanging(int value);
    partial void OnNhanVienIDChanged();
    partial void OnConNguoiIDChanging(int value);
    partial void OnConNguoiIDChanged();
    #endregion
		
		public NhanVien()
		{
			this._CuocGois = new EntitySet<CuocGoi>(new Action<CuocGoi>(this.attach_CuocGois), new Action<CuocGoi>(this.detach_CuocGois));
			this._DanhSachChucVus = new EntitySet<DanhSachChucVu>(new Action<DanhSachChucVu>(this.attach_DanhSachChucVus), new Action<DanhSachChucVu>(this.detach_DanhSachChucVus));
			this._QuaTangs = new EntitySet<QuaTang>(new Action<QuaTang>(this.attach_QuaTangs), new Action<QuaTang>(this.detach_QuaTangs));
			this._ConNguoi = default(EntityRef<ConNguoi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhanVienID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int NhanVienID
		{
			get
			{
				return this._NhanVienID;
			}
			set
			{
				if ((this._NhanVienID != value))
				{
					this.OnNhanVienIDChanging(value);
					this.SendPropertyChanging();
					this._NhanVienID = value;
					this.SendPropertyChanged("NhanVienID");
					this.OnNhanVienIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConNguoiID", DbType="Int NOT NULL")]
		public int ConNguoiID
		{
			get
			{
				return this._ConNguoiID;
			}
			set
			{
				if ((this._ConNguoiID != value))
				{
					if (this._ConNguoi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnConNguoiIDChanging(value);
					this.SendPropertyChanging();
					this._ConNguoiID = value;
					this.SendPropertyChanged("ConNguoiID");
					this.OnConNguoiIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_CuocGoi", Storage="_CuocGois", ThisKey="NhanVienID", OtherKey="NhanVienID")]
		public EntitySet<CuocGoi> CuocGois
		{
			get
			{
				return this._CuocGois;
			}
			set
			{
				this._CuocGois.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_DanhSachChucVu", Storage="_DanhSachChucVus", ThisKey="NhanVienID", OtherKey="NhanVienID")]
		public EntitySet<DanhSachChucVu> DanhSachChucVus
		{
			get
			{
				return this._DanhSachChucVus;
			}
			set
			{
				this._DanhSachChucVus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_QuaTang", Storage="_QuaTangs", ThisKey="NhanVienID", OtherKey="NhanVienID")]
		public EntitySet<QuaTang> QuaTangs
		{
			get
			{
				return this._QuaTangs;
			}
			set
			{
				this._QuaTangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ConNguoi_NhanVien", Storage="_ConNguoi", ThisKey="ConNguoiID", OtherKey="ConNguoiID", IsForeignKey=true)]
		public ConNguoi ConNguoi
		{
			get
			{
				return this._ConNguoi.Entity;
			}
			set
			{
				ConNguoi previousValue = this._ConNguoi.Entity;
				if (((previousValue != value) 
							|| (this._ConNguoi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ConNguoi.Entity = null;
						previousValue.NhanViens.Remove(this);
					}
					this._ConNguoi.Entity = value;
					if ((value != null))
					{
						value.NhanViens.Add(this);
						this._ConNguoiID = value.ConNguoiID;
					}
					else
					{
						this._ConNguoiID = default(int);
					}
					this.SendPropertyChanged("ConNguoi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CuocGois(CuocGoi entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_CuocGois(CuocGoi entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_DanhSachChucVus(DanhSachChucVu entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_DanhSachChucVus(DanhSachChucVu entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_QuaTangs(QuaTang entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_QuaTangs(QuaTang entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QuaTang")]
	public partial class QuaTang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _QuaTangID;
		
		private int _KHID;
		
		private string _TenQua;
		
		private double _GiaTri;
		
		private System.Nullable<System.DateTime> _NgayGui;
		
		private System.Nullable<bool> _DaNhan;
		
		private int _NhanVienID;
		
		private bool _DaGui;
		
		private System.DateTime _NgayLenKeHoach;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnQuaTangIDChanging(int value);
    partial void OnQuaTangIDChanged();
    partial void OnKHIDChanging(int value);
    partial void OnKHIDChanged();
    partial void OnTenQuaChanging(string value);
    partial void OnTenQuaChanged();
    partial void OnGiaTriChanging(double value);
    partial void OnGiaTriChanged();
    partial void OnNgayGuiChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayGuiChanged();
    partial void OnDaNhanChanging(System.Nullable<bool> value);
    partial void OnDaNhanChanged();
    partial void OnNhanVienIDChanging(int value);
    partial void OnNhanVienIDChanged();
    partial void OnDaGuiChanging(bool value);
    partial void OnDaGuiChanged();
    partial void OnNgayLenKeHoachChanging(System.DateTime value);
    partial void OnNgayLenKeHoachChanged();
    #endregion
		
		public QuaTang()
		{
			this._KhachHang = default(EntityRef<KhachHang>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuaTangID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int QuaTangID
		{
			get
			{
				return this._QuaTangID;
			}
			set
			{
				if ((this._QuaTangID != value))
				{
					this.OnQuaTangIDChanging(value);
					this.SendPropertyChanging();
					this._QuaTangID = value;
					this.SendPropertyChanged("QuaTangID");
					this.OnQuaTangIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KHID", DbType="Int NOT NULL")]
		public int KHID
		{
			get
			{
				return this._KHID;
			}
			set
			{
				if ((this._KHID != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKHIDChanging(value);
					this.SendPropertyChanging();
					this._KHID = value;
					this.SendPropertyChanged("KHID");
					this.OnKHIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQua", DbType="NVarChar(100)")]
		public string TenQua
		{
			get
			{
				return this._TenQua;
			}
			set
			{
				if ((this._TenQua != value))
				{
					this.OnTenQuaChanging(value);
					this.SendPropertyChanging();
					this._TenQua = value;
					this.SendPropertyChanged("TenQua");
					this.OnTenQuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTri", DbType="Float NOT NULL")]
		public double GiaTri
		{
			get
			{
				return this._GiaTri;
			}
			set
			{
				if ((this._GiaTri != value))
				{
					this.OnGiaTriChanging(value);
					this.SendPropertyChanging();
					this._GiaTri = value;
					this.SendPropertyChanged("GiaTri");
					this.OnGiaTriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGui", DbType="Date")]
		public System.Nullable<System.DateTime> NgayGui
		{
			get
			{
				return this._NgayGui;
			}
			set
			{
				if ((this._NgayGui != value))
				{
					this.OnNgayGuiChanging(value);
					this.SendPropertyChanging();
					this._NgayGui = value;
					this.SendPropertyChanged("NgayGui");
					this.OnNgayGuiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaNhan", DbType="Bit")]
		public System.Nullable<bool> DaNhan
		{
			get
			{
				return this._DaNhan;
			}
			set
			{
				if ((this._DaNhan != value))
				{
					this.OnDaNhanChanging(value);
					this.SendPropertyChanging();
					this._DaNhan = value;
					this.SendPropertyChanged("DaNhan");
					this.OnDaNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhanVienID", DbType="Int NOT NULL")]
		public int NhanVienID
		{
			get
			{
				return this._NhanVienID;
			}
			set
			{
				if ((this._NhanVienID != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNhanVienIDChanging(value);
					this.SendPropertyChanging();
					this._NhanVienID = value;
					this.SendPropertyChanged("NhanVienID");
					this.OnNhanVienIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaGui", DbType="Bit NOT NULL")]
		public bool DaGui
		{
			get
			{
				return this._DaGui;
			}
			set
			{
				if ((this._DaGui != value))
				{
					this.OnDaGuiChanging(value);
					this.SendPropertyChanging();
					this._DaGui = value;
					this.SendPropertyChanged("DaGui");
					this.OnDaGuiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLenKeHoach", DbType="Date NOT NULL")]
		public System.DateTime NgayLenKeHoach
		{
			get
			{
				return this._NgayLenKeHoach;
			}
			set
			{
				if ((this._NgayLenKeHoach != value))
				{
					this.OnNgayLenKeHoachChanging(value);
					this.SendPropertyChanging();
					this._NgayLenKeHoach = value;
					this.SendPropertyChanged("NgayLenKeHoach");
					this.OnNgayLenKeHoachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_QuaTang", Storage="_KhachHang", ThisKey="KHID", OtherKey="KhachHangID", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.QuaTangs.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.QuaTangs.Add(this);
						this._KHID = value.KhachHangID;
					}
					else
					{
						this._KHID = default(int);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_QuaTang", Storage="_NhanVien", ThisKey="NhanVienID", OtherKey="NhanVienID", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.QuaTangs.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.QuaTangs.Add(this);
						this._NhanVienID = value.NhanVienID;
					}
					else
					{
						this._NhanVienID = default(int);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Quyen")]
	public partial class Quyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _QuyenID;
		
		private bool _PhanQuyen;
		
		private bool _HoTroGiaoTiepKH;
		
		private bool _XoaCuocGoi;
		
		private bool _QLTTCaNhanKH;
		
		private bool _SuaTTKH;
		
		private bool _XoaTTKH;
		
		private bool _QLTTNV;
		
		private bool _BaoCaoThongKe;
		
		private bool _QLTTQuaTang;
		
		private bool _XemTTQuaTang;
		
		private bool _XemTTNhanVien;
		
		private EntitySet<ChucVu> _ChucVus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnQuyenIDChanging(int value);
    partial void OnQuyenIDChanged();
    partial void OnPhanQuyenChanging(bool value);
    partial void OnPhanQuyenChanged();
    partial void OnHoTroGiaoTiepKHChanging(bool value);
    partial void OnHoTroGiaoTiepKHChanged();
    partial void OnXoaCuocGoiChanging(bool value);
    partial void OnXoaCuocGoiChanged();
    partial void OnQLTTCaNhanKHChanging(bool value);
    partial void OnQLTTCaNhanKHChanged();
    partial void OnSuaTTKHChanging(bool value);
    partial void OnSuaTTKHChanged();
    partial void OnXoaTTKHChanging(bool value);
    partial void OnXoaTTKHChanged();
    partial void OnQLTTNVChanging(bool value);
    partial void OnQLTTNVChanged();
    partial void OnBaoCaoThongKeChanging(bool value);
    partial void OnBaoCaoThongKeChanged();
    partial void OnQLTTQuaTangChanging(bool value);
    partial void OnQLTTQuaTangChanged();
    partial void OnXemTTQuaTangChanging(bool value);
    partial void OnXemTTQuaTangChanged();
    partial void OnXemTTNhanVienChanging(bool value);
    partial void OnXemTTNhanVienChanged();
    #endregion
		
		public Quyen()
		{
			this._ChucVus = new EntitySet<ChucVu>(new Action<ChucVu>(this.attach_ChucVus), new Action<ChucVu>(this.detach_ChucVus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuyenID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int QuyenID
		{
			get
			{
				return this._QuyenID;
			}
			set
			{
				if ((this._QuyenID != value))
				{
					this.OnQuyenIDChanging(value);
					this.SendPropertyChanging();
					this._QuyenID = value;
					this.SendPropertyChanged("QuyenID");
					this.OnQuyenIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhanQuyen", DbType="Bit NOT NULL")]
		public bool PhanQuyen
		{
			get
			{
				return this._PhanQuyen;
			}
			set
			{
				if ((this._PhanQuyen != value))
				{
					this.OnPhanQuyenChanging(value);
					this.SendPropertyChanging();
					this._PhanQuyen = value;
					this.SendPropertyChanged("PhanQuyen");
					this.OnPhanQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTroGiaoTiepKH", DbType="Bit NOT NULL")]
		public bool HoTroGiaoTiepKH
		{
			get
			{
				return this._HoTroGiaoTiepKH;
			}
			set
			{
				if ((this._HoTroGiaoTiepKH != value))
				{
					this.OnHoTroGiaoTiepKHChanging(value);
					this.SendPropertyChanging();
					this._HoTroGiaoTiepKH = value;
					this.SendPropertyChanged("HoTroGiaoTiepKH");
					this.OnHoTroGiaoTiepKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XoaCuocGoi", DbType="Bit NOT NULL")]
		public bool XoaCuocGoi
		{
			get
			{
				return this._XoaCuocGoi;
			}
			set
			{
				if ((this._XoaCuocGoi != value))
				{
					this.OnXoaCuocGoiChanging(value);
					this.SendPropertyChanging();
					this._XoaCuocGoi = value;
					this.SendPropertyChanged("XoaCuocGoi");
					this.OnXoaCuocGoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QLTTCaNhanKH", DbType="Bit NOT NULL")]
		public bool QLTTCaNhanKH
		{
			get
			{
				return this._QLTTCaNhanKH;
			}
			set
			{
				if ((this._QLTTCaNhanKH != value))
				{
					this.OnQLTTCaNhanKHChanging(value);
					this.SendPropertyChanging();
					this._QLTTCaNhanKH = value;
					this.SendPropertyChanged("QLTTCaNhanKH");
					this.OnQLTTCaNhanKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SuaTTKH", DbType="Bit NOT NULL")]
		public bool SuaTTKH
		{
			get
			{
				return this._SuaTTKH;
			}
			set
			{
				if ((this._SuaTTKH != value))
				{
					this.OnSuaTTKHChanging(value);
					this.SendPropertyChanging();
					this._SuaTTKH = value;
					this.SendPropertyChanged("SuaTTKH");
					this.OnSuaTTKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XoaTTKH", DbType="Bit NOT NULL")]
		public bool XoaTTKH
		{
			get
			{
				return this._XoaTTKH;
			}
			set
			{
				if ((this._XoaTTKH != value))
				{
					this.OnXoaTTKHChanging(value);
					this.SendPropertyChanging();
					this._XoaTTKH = value;
					this.SendPropertyChanged("XoaTTKH");
					this.OnXoaTTKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QLTTNV", DbType="Bit NOT NULL")]
		public bool QLTTNV
		{
			get
			{
				return this._QLTTNV;
			}
			set
			{
				if ((this._QLTTNV != value))
				{
					this.OnQLTTNVChanging(value);
					this.SendPropertyChanging();
					this._QLTTNV = value;
					this.SendPropertyChanged("QLTTNV");
					this.OnQLTTNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaoCaoThongKe", DbType="Bit NOT NULL")]
		public bool BaoCaoThongKe
		{
			get
			{
				return this._BaoCaoThongKe;
			}
			set
			{
				if ((this._BaoCaoThongKe != value))
				{
					this.OnBaoCaoThongKeChanging(value);
					this.SendPropertyChanging();
					this._BaoCaoThongKe = value;
					this.SendPropertyChanged("BaoCaoThongKe");
					this.OnBaoCaoThongKeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QLTTQuaTang", DbType="Bit NOT NULL")]
		public bool QLTTQuaTang
		{
			get
			{
				return this._QLTTQuaTang;
			}
			set
			{
				if ((this._QLTTQuaTang != value))
				{
					this.OnQLTTQuaTangChanging(value);
					this.SendPropertyChanging();
					this._QLTTQuaTang = value;
					this.SendPropertyChanged("QLTTQuaTang");
					this.OnQLTTQuaTangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XemTTQuaTang", DbType="Bit NOT NULL")]
		public bool XemTTQuaTang
		{
			get
			{
				return this._XemTTQuaTang;
			}
			set
			{
				if ((this._XemTTQuaTang != value))
				{
					this.OnXemTTQuaTangChanging(value);
					this.SendPropertyChanging();
					this._XemTTQuaTang = value;
					this.SendPropertyChanged("XemTTQuaTang");
					this.OnXemTTQuaTangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XemTTNhanVien", DbType="Bit NOT NULL")]
		public bool XemTTNhanVien
		{
			get
			{
				return this._XemTTNhanVien;
			}
			set
			{
				if ((this._XemTTNhanVien != value))
				{
					this.OnXemTTNhanVienChanging(value);
					this.SendPropertyChanging();
					this._XemTTNhanVien = value;
					this.SendPropertyChanged("XemTTNhanVien");
					this.OnXemTTNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Quyen_ChucVu", Storage="_ChucVus", ThisKey="QuyenID", OtherKey="QuyenID")]
		public EntitySet<ChucVu> ChucVus
		{
			get
			{
				return this._ChucVus;
			}
			set
			{
				this._ChucVus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChucVus(ChucVu entity)
		{
			this.SendPropertyChanging();
			entity.Quyen = this;
		}
		
		private void detach_ChucVus(ChucVu entity)
		{
			this.SendPropertyChanging();
			entity.Quyen = null;
		}
	}
}
#pragma warning restore 1591
